name: Test

on:
  push:
    branches:
      - 'master'
      - 'dev*'
  pull_request:
  schedule:
    - cron: "0 23 * * 0-4"   # 08:00 JST, Monday to Friday

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - redmine-repository: 'redmica/redmica'
            redmine-version: 'stable-4.0'
            ruby-version: '3.4'
          - redmine-repository: 'redmine/redmine'
            redmine-version: 'master'
            ruby-version: '3.4'

    steps:
    - uses: hidakatsuya/action-setup-redmine@v3.0.1
      with:
        repository: ${{ matrix.redmine-repository }}
        version: ${{ matrix.redmine-version }}
        ruby-version: ${{ matrix.ruby-version }}
        database: 'postgres:14'

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        path: plugins/redmine_issues_panel

    - run: bin/rails redmine:plugins:migrate NAME=redmine_issues_panel RAILS_ENV=test

    - run: bin/rails redmine:plugins:test NAME=redmine_issues_panel
